version: "3.2"

services:
  
  electrs:
    image: electrs-app:latest
    container_name: electrs
    build:
      context: ./electrs
    env_file:
      - ./.env
      - ./conf/docker-bitcoind.conf
      - ./conf/docker-electrs.conf
    command: "/home/user/restart.sh"
    depends_on:
      - bitcoind
      - db
      - tor
    volumes:
      - ./conf/docker-electrs.toml:/home/user/.electrs/config.toml:ro
      - data-electrs:/home/user
      - ./electrs/restart.sh:/home/user/restart.sh
    restart: on-failure
    networks:
      dojonet:
        ipv4_address: 172.28.1.10

volumes:
  data-electrs:

